### ISSUE TITLE
配置：通过验证后，如何删掉用户回复的验证码？

### ISSUE THREAD

**Issue by 1c7** [jqs7/zwei#24]
![image](https://user-images.githubusercontent.com/1804755/51649891-2156da00-1fc1-11e9-8325-1cff6abde21f.png)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/51649909-316eb980-1fc1-11e9-8b1a-f65cf2f688b1.png)

**Comment by jqs7** [comment]
通过验证后会自动删掉的

**Comment by 1c7** [comment]
那应该是我没给够权限，不好意思。感谢回复。我先关掉这个 issue
